kind: ReplicationController
apiVersion: v1
metadata:
  name: myapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        uses: redis
    spec:
      containers:
      - name: myapp
        image: m1.dlr.com:5000/myapp
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
  selector:
    name: myapp
