kind: ReplicationController
apiVersion: v1
metadata:
    name: myredis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: m1.dlr.com:5000/redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redissvc
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    name: redis
